### ISSUE TITLE
Package suggestions

### ISSUE THREAD

**Issue by kadyb** [cran-task-views/Spatial#16]
Do you think the following packages are worth including?
`{exactextractr}` - fast and accurate summary of raster values on polygonal areas (known as _zonal statistics_)
`{geos}` - high-performance bindings to the Open Source Geometry Engine (GEOS) library
`{s2}` - bindings to S2Geometry library for geometric calculations on the sphere

**Comment by rsbivand** [comment]
PR please; s2 is obvious so that is obvious.

**Comment by rsbivand** [comment]
Added **s2** in `Data processing - general`, moved **geos** to the same subsection and added **libgeos** with a note about version mix problems.

**Comment by kadyb** [comment]
Thanks!
