### ISSUE TITLE
broken links to stars github repo

### ISSUE THREAD

**Issue by jamesdamillington** [cran-task-views/Spatial#20]
Several links to the [stars r-spatial github repo](https://github.com/r-spatial/stars) are broken because `r github("rspatial/stars")` should be `r github("r-spatial/stars")` (in [Spatial.md](https://github.com/cran-task-views/Spatial/blob/main/Spatial.md))

**Comment by Nowosad** [comment]
Thank you James for letting us know. Would it be possible that you create a pull request fixing this issue?

**Comment by jamesdamillington** [comment]
Sure. Will try to do later today
