### ISSUE TITLE
Package suggestion

### ISSUE THREAD

**Issue by Jo-Schie** [cran-task-views/Spatial#37]
Hello,

I was wondering whether it was possible to add our [mapme.biodiversity](https://cran.r-project.org/web/packages/mapme.biodiversity/index.html) package to the task-view under **Specific geospatial data sources of interest**. 

Description text could be something along the lines of "allows to download and process a number open datasets related to biodiversity conservation providing efficient routines and parallelization options. Datasets include among others the [Global Forest Watch](https://www.globalforestwatch.org/), [ESA/Copernicus Landcover](https://land.copernicus.eu/global/products/lc), [Worldclim ](https://www.worldclim.org/) and [NASA FIRMS](https://firms.modaps.eosdis.nasa.gov/active_fire/)" .

Could be helpful for us to attract more users and grow the community. :)

**Comment by Nowosad** [comment]
Dear @Jo-Schie could you prepare a pull request with this addition?

**Comment by rsbivand** [comment]
@Jo-Schie May we expect a PR, please?

**Comment by Jo-Schie** [comment]
just send a PR. Sorry for the delay.

**Comment by rsbivand** [comment]
Fixed by #41
