### ISSUE TITLE
Suggested minimal requirements for a new packages to be included in the spatial CRAN task view

### ISSUE THREAD

**Issue by Nowosad** [cran-task-views/Spatial#38]
@rsbivand what do you think about the following statement? Do you have any suggestions on how to improve it? what do you think about adding it to the repo's README?

> We encourage the packages authors to follow minimum standards for their package to be included in the Spatial CRAN Task View:
> - The package must be related to spatial data reading/writing, handling, processing, or analyzing
> - The package should be actively maintained 
> - The package should have extended documentation in the form of a vignette, blog post, scientific article, technical report, or video. In other words, there should be a way for new users to get started with using the package

**Comment by rsbivand** [comment]
Sorry for delay; yes, this looks fine. Perhaps a final sub-point: Packages already listed, but without extended documentation are encouraged to add more documentation in a forthcoming revision of the package.

**Comment by Nowosad** [comment]
@rsbivand see https://github.com/cran-task-views/Spatial/pull/39
