### ISSUE TITLE
Package 'ModelMap' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Spatial#42]
Package [ModelMap](https://CRAN.R-project.org/package=ModelMap) is currently listed in CRAN Task View [Spatial](https://CRAN.R-project.org/view=Spatial) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by Nowosad** [comment]
@rsbivand should we just try to email this package author? The CRAN website says "Archived on 2022-10-07 as email to the maintainer is undeliverable.", while all of the checks seem to be fine (https://cran-archive.r-project.org/web/checks/2022/2022-10-08_check_results_ModelMap.html). Additionally, the same author has another package still on CRAN (with the same email address mentioned) -- https://cran.r-project.org/package=PresenceAbsence.

**Comment by rsbivand** [comment]
Yes; if the email bounces, try at https://www.fs.usda.gov/rmrs/people/eafreeman perhaps?

**Comment by Nowosad** [comment]
I contacted the author and the package is back on CRAN (https://cran.r-project.org/package=ModelMap).
