### ISSUE TITLE
Proposal: add `spaths` package

### ISSUE THREAD

**Issue by ChristianDueben** [cran-task-views/Spatial#72]
Package: https://cran.r-project.org/package=spaths (CRAN), https://github.com/ChristianDueben/spaths (GitHub). Vignette: https://cran.r-project.org/web/packages/spaths/vignettes/spaths_introduction.html.

`spaths` computes shortest paths in grids, incl. in SpatRasters and RasterLayers. It can account for (moving) barriers and custom transition functions. The vignette lists reasons for developing this package, its design principles, how to use its functions, etc.

The package is actively maintained and will cover a larger set of graph-theoretical methods in the future.

**Comment by Nowosad** [comment]
Dear @ChristianDueben could you prepare a pull request adding your package to the Data processing - general section in the same point as [gdistance](https://cran.r-project.org/web/packages/gdistance/index.html) (or do you have a suggestion of a better place?)?
