### ISSUE TITLE
Remove Twitter (X)?

### ISSUE THREAD

**Issue by kadyb** [cran-task-views/Spatial#86]
The description says:

> Using the #rspatial tag on [Twitter](https://twitter.com/) and [Mastodon](https://joinmastodon.org/) may also be worth trying, or browsing traffic using that tag (among others).

Maybe this is a good time to delete Twitter as most have moved to Mastodon and other social media?

**Comment by rsbivand** [comment]
@kadyb Good idea, done. Do you know of a bsky tag matching `#rspatial` ? Or a resource listing for that platform?

**Comment by kadyb** [comment]
BlueSky has the exact same hashtag (https://bsky.app/hashtag/rspatial), but it's not as popular as Mastodon. Sadly, `#rspatial` was many times more popular on Twitter, unfortunately. There are other hashtags, e.g. `#gischat`, `#gis`, `#maps` or `#geospatial`, but they are very general. It seems that Mastodon is our main home for now.

Happy Christmas and New Year!

**Comment by rsbivand** [comment]
Thanks! Best wishes for Christmas and the New Year!
